=== franklindyer/ResuML/resume.dtd
<!ELEMENT resume
    (identity, contact?, skills?)>
<!ELEMENT identity
    (name, dob?, pronouns?)>
<!ELEMENT name (#PCDATA)>

<!ELEMENT dob (year, month, day)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT month (#PCDATA)>
<!ELEMENT day (#PCDATA)>

<!ELEMENT pronouns (#PCDATA)>

<!ELEMENT contact
    (phone | email | weburl)*>
<!ELEMENT phone (#PCDATA)>
<!ATTLIST phone
    type (home | work | cell) #IMPLIED>
<!ELEMENT email (#PCDATA)>
<!ATTLIST email
    type (personal | work) #IMPLIED>
<!ELEMENT weburl (#PCDATA)>
<!ELEMENT social (#PCDATA)>
<!ATTLIST social
    site CDATA #REQUIRED>

<!ELEMENT skills
    (language | tech | proglang | softskill)+>
<!ENTITY % skill.att
    'tags   CDATA   #IMPLIED
     cert   CDATA   #IMPLIED
     level  CDATA   #IMPLIED'>
<!ELEMENT language  (#PCDATA)>
<!ATTLIST language  %skill.att;>
<!ELEMENT tech      (#PCDATA)>
<!ATTLIST tech      %skill.att;>
<!ELEMENT proglang  (#PCDATA)>
<!ATTLIST proglang  %skill.att;>
<!ELEMENT softskill (#PCDATA)>
<!ATTLIST softskill %skill.att;>

=== franklindyer/ResuML/data/lomax.xml
<?xml version="1.0"?>
<!DOCTYPE resume SYSTEM "../resume.dtd">
<resume>

<identity>
    <name>Hollis Lomax</name>
    <pronouns>He/him</pronouns>
</identity>

<contact>
    <email type="work">hlomax@missouri.edu</email>
</contact>

<skills>
    <tech tags="writing">Microsoft Word</tech>
    <tech tags="stats">Microsoft Excel</tech>
    <tech tags="design">Microsoft Powerpoint</tech>

    <proglang tags="writing">LaTeX</proglang> 
    <proglang tags="web,writing">HTML</proglang> 
    <proglang tags="web,design">CSS</proglang> 

    <language level="native">English</language>
    <language level="flient" cert="Goethe-Institut C1">German</language>

    <softskill tags="writing">Literary analysis</softskill>
    <softskill tags="teaching">Teaching</softskill>
</skills>

</resume>
